- name: Deploy web page
  hosts: webserver
  become: yes

  tasks:
    - name: copy index page
      copy:
        src: ../files/index.html
        dest: /var/www/html/index.html

        owner: root
        group: root
        mode: '0644'
